BEGIN TRANSACTION;
CREATE TABLE `types` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE "settings" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`profile`	INTEGER NOT NULL,
	`device`	INTEGER NOT NULL,
	`setting`	TEXT NOT NULL,
	FOREIGN KEY(`profile`) REFERENCES `profiles`(`id`),
	FOREIGN KEY(`device`) REFERENCES `devices`(`id`)
);
CREATE TABLE `profiles` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE "devices" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`mac`	TEXT NOT NULL UNIQUE,
	`type`	INTEGER NOT NULL,
	`ip`	TEXT,
	FOREIGN KEY(`type`) REFERENCES `types`(`id`)
);
COMMIT;
